### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by jeremyahuang** [apexskier/nova-typescript#128] opened 2020-11-12 16:50 UTC
The extension fails to install when attempting to install it, and then fails each time it is loaded (when opening Nova or when enabling the extension after disabling it). 

**To reproduce**

1. Go to the extensions Browser
2. Install TypeScript

**Expected behavior**

The TypeScript extensions installed successfully. 

**Screenshots**
<img width="459" alt="Screen Shot 2020-11-12 at 11 43 10 AM" src="https://user-images.githubusercontent.com/14279945/98968863-412ff880-24dc-11eb-9214-3b0a34052866.png">

**Environment**

- Nova version: 2.1 (215812)
- Extension version: 2.0.1
- TypeScript version: 3.9.7
- Sidebar information: Status Failed to install, Typescript Version [End of Line]
- macOS version: 10.15.7
- NodeJS information:
  - node version: 13.14.0
  - pnpm version: 4.12.0
  - installation method: homebrew, hnvm, pnpm

**Extension console output**

```TypeScript[11:49:54.664000] reloading...

TypeScript[11:49:54.665000] dependencyManagement: claimed lock

TypeScript[11:49:54.713000] dependencyManagement: installing: cat: /Users/jeremy.huang/Library/Application: No such file or directory

TypeScript[11:49:54.714000] dependencyManagement: installing: cat: Support/Nova/Extensions/apexskier.typescript/dependencyManagement/package.json: No such file or directory

TypeScript[11:49:54.716000] dependencyManagement: clearing lock
```

```TypeScript[11:51:57.615000] activating...

TypeScript[11:51:57.619000] dependencyManagement: claimed lock

TypeScript[11:51:57.676000] dependencyManagement: installing: cat: /Users/jeremy.huang/Library/Application: No such file or directory

TypeScript[11:51:57.676000] dependencyManagement: installing: cat: Support/Nova/Extensions/apexskier.typescript/dependencyManagement/package.json: No such file or directory

TypeScript[11:51:57.680000] dependencyManagement: clearing lock

TypeScript[11:51:57.681000] Failed to activate

TypeScript[11:51:57.681000] Error: Failed to install:

cat: /Users/jeremy.huang/Library/Application: No such file or directory
cat: Support/Nova/Extensions/apexskier.typescript/dependencyManagement/package.json: No such file or directory


TypeScript[11:51:57.681000] activated
```

**Additional context**

**Comment by apexskier** [comment] 2020-11-13 13:00
This looks like something's trying to read your "Application Support" directory, but isn't properly wrapping the directory name in quotes before processing it with a shell.

I'm not sure where `cat` is coming from - I don't think it's from extension code, but it might be from `hnvm` or `pnpm`. The "Failed to install" message is coming from [here](https://github.com/apexskier/nova-extension-utils/blob/7c087fc19575bd2890732d39fba381f38a8d364e/src/dependencyManagement.ts#L182), which indicates this error comes from the command `/usr/bin/env npm install`.

Can you please try running [the installation](https://github.com/apexskier/nova-extension-utils/blob/main/src/dependencyManagement.ts#L164-L171) manually within a terminal (let me know if the shell is something other than bash), and reporting what you get (stdout, stderr, and exit code)? You can use this command:

```
(NO_UPDATE_NOTIFIER=true cd "/Users/jeremy.huang/Library/Application Support/Nova/Extensions/apexskier.typescript/dependencyManagement/" && /usr/bin/env npm install)
```

**Comment by apexskier** [comment] 2020-11-13 13:12
I'm guessing this is caused by `hnvm`. From [the README](https://github.com/UrbanCompass/hnvm#usage)

> HNVM reads the version of node/pnpm/yarn set in your package.json file' "engines" field.

[This line](https://github.com/UrbanCompass/hnvm/blob/209ebf040b449aa737fa5c31292f268b1feaf121/lib/config.sh#L51) should wrap `$pkg_json` in quotes. 

I opened https://github.com/UrbanCompass/hnvm/pull/12 to fix the immediate issue, but can't guarantee there won't be others with `hnvm`. I'm going to close this issue for now, though, since the root cause isn't nova-typescript.

**Closed by apexskier** 2020-11-13 13:12 UTC
Labels: bug

**Comment by jeremyahuang** [comment] 2020-11-16 16:10
Thank you!
