### ISSUE TITLE
Extension appears to be running but doesn't provide any functionality

### ISSUE THREAD

**Issue by halfnibble** [apexskier/nova-typescript#59] opened 2020-09-04 19:45 UTC
Unfortunately, the extension does not work at all (except for syntax highlighting) in Nova 1.0b20.

**To Reproduce**

* Update Nova to 1.0b20
* Edit any TypeScript file and try to access properties on imported, typed objects.
* Or even try something simpler like, let test: number = "hello";
* No errors. :(

**Expected behavior**
I would expect autocomplete to show a list of properties for typed objects.

And I would expect obvious type assignment errors to display an error.

Note: this worked in 1.0b19.

**Screenshots**

**Environment (please complete the following information):**
* OS: macOS 10.15.6 (19G2021)
* Nova version: 1.0b20 Build 199815
* Extension version: 1.6.1
* TypeScript version: 3.7.5
* Sidebar information: Running. Version 4.0.2
* NodeJS information:
   - node version: 10.16.3
   - npm version: 6.11.3
   - installation method: Rush.js > pnpm

**Additional context**
The extension was working until the most recent Nova update (and the extension has not changed to my knowledge).

Since I am working in a monorepo, I also tried setting the path to the TypeScript server, and I still don't get TypeScript support in Nova.

**npm-debug.log**

Nothing output.

**Comment by halfnibble** [comment] 2020-09-05 05:17
Update: this only happens in one of my two repos. I have no idea why. Is there any way to get more debugging info from the extension? It looks like it's not even running on my one repo despite reporting "activated"

**Comment by apexskier** [comment] 2020-09-07 07:06
The extension is working for me on Beta 20, however, I do see some stuff in the extension console that indicates some changes to the runtime behavior that could be problematic.

Specifically, I haven't see this before - it looks like Panic might have changed the execution environment for the language server to be readonly.
<img width="400" alt="Screen Shot 2020-09-07 at 08 51 23" src="https://user-images.githubusercontent.com/329222/92357120-a126af00-f0e7-11ea-9c0e-21043915089e.png">

If you clone this project locally and [run it locally](https://github.com/apexskier/nova-typescript/blob/master/CONTRIBUTING.md#running-locally) you'll see more information in the extension console (I hide a few things when not in dev mode).

**Comment by apexskier** [comment] 2020-09-07 07:11
Also - you indicated that your expected typescript version is 3.7.5 and the sidebar says you're getting 4.0.2. I haven't used Rush.js or pnpm, but they could be causing the wrong version of typescript to be used, which could cause the issue.

**Comment by halfnibble** [comment] 2020-09-08 08:54
I don't know what happened, but it started working again. 🤷‍♂️ I guess we can close this issue.

Very, very odd. Do you want me to file a bug with the Nova team about the readonly language server environment?

**Comment by joshdick** [comment] 2020-09-10 04:40
FWIW I seem to be having the same issue, with b20. the sidebar shows that the TypeScript server is running but the extension is otherwise not working.

**Comment by apexskier** [comment] 2020-09-10 06:23
@halfnibble Forgot to mention - I filed a bug for the readonly environment [here](https://dev.panic.com/panic/nova-issues/-/issues/1575).

**Comment by apexskier** [comment] 2020-09-10 06:24
@joshdick Are you able to clone this and [run locally](https://github.com/apexskier/nova-typescript/blob/master/CONTRIBUTING.md#running-locally)? I'd like to see what the Extension Console says for someone who can reproduce.

**Comment by joshdick** [comment] 2020-09-11 17:21
@apexskier A few interesting things:

I tried upgrading Nova from b20 to v1.0 and starting completely fresh by removing all of Nova's supporting files with [AppCleaner](https://freemacsoft.net/appcleaner/). After doing that:

* The "run locally" test you mentioned works fine and shows errors as expected inside the locally-cloned extension project.
* Running the release version extension installed via Extension Library **now causes Nova to hard-crash when I attempt to open a `.ts` file in my own project.**

**Comment by apexskier** [comment] 2020-09-14 15:41
> * Running the release version extension installed via Extension Library **now causes Nova to hard-crash when I attempt to open a `.ts` file in my own existing project.** Disabling the extension stops the hard crashing. This happens even when `nova-typescript` is the only extension enabled.

Yikes. Can you [file a bug with Panic](https://dev.panic.com/panic/nova-issues/-/issues/new) for this? Any hard crashes indicate something not being handled gracefully by Nova, and will obscure any info the extension is providing in the console.

**Comment by apexskier** [comment] 2020-09-14 15:47
> Unfortunately, the extension does not work at all (except for syntax highlighting)

Also, I forgot to mention - this extension doesn't provide syntax highlighting, that's something Nova provides directly.

**Comment by chillax** [comment] 2020-09-15 06:24
> * Running the release version of the extension installed via Extension Library **now causes Nova to hard-crash when I attempt to open a `.ts` file in my own existing project.** Disabling the extension stops the hard crashing. This happens even when `nova-typescript` is the only extension enabled.

After upgrading to 1.0 having this extension enabled causes Nova to crash every time I try to open/close a tab in a project, even in non-TS projects. I submitted a problem report via the Panic's new issue form.

**Comment by ishanray** [comment] 2020-09-17 03:06
This doesn't work and is very buggy. Also autocomplete of any kind doesn't show up.

**Comment by apexskier** [comment] 2020-09-18 17:57
@ishanray Can you please provide some more details? Anything in the extension console? Does this reproduce if you run the extension locally?

**Comment by halfnibble** [comment] 2020-09-20 00:33
Unrelated to my original issue (which thankfully resolved itself 🤞), I saw this note on the typescript-language-server repo.
"looking for maintainers"
https://github.com/theia-ide/typescript-language-server/issues/141

Do we know how Theia is able to use the VS Code extension, and is that possible for Nova?

**Comment by apexskier** [comment] 2020-09-20 08:03
My guess is that Theia is providing a compatible extension api for VSCode, which would be in Panic's hands. My opinion is that the bet on the Language Server Protocol is the right one, but Nova's support is still pretty basic. Since Microsoft is behind Typescript, VSCode, and LSP I'm hoping things converge (https://github.com/microsoft/TypeScript/issues/39459).

I haven't run into any missing functionality yet, but I'd consider taking over maintenance of `typescript-language-server` if we discover any bugs or missing features.

**Comment by apexskier** [comment] 2020-09-20 09:35
This issue is getting a little messy and I'm going to be closing it, since it's pre-official release and I've updated my bug report template since.

Sounds like @halfnibble and @joshdick aren't experiencing it anymore, @chillax's issue sounds more like https://github.com/apexskier/nova-typescript/issues/74, and @ishanray please file a new issue with more details if you're still experiencing this as well on the latest release.

**Closed by apexskier** 2020-09-20 09:35 UTC
Labels: bug, help wanted

**Comment by joshdick** [comment] 2020-09-23 21:48
I am actually still having crashing issues with Nova 1.1 and v1.7.0 of this extension, but will prod #74 instead.
