### ISSUE TITLE
TypeScript server is failing to start

### ISSUE THREAD

**Issue by widersky** [apexskier/nova-typescript#455] opened 2023-01-18 09:14 UTC
Sometimes the TS server does not start at all - only an error is shown as in the attachment. Clicking on "restart" does not help.

**To reproduce**

1. Open Nova
2. Open TSX file

**Expected behavior**

No error

**Screenshots**

![image](https://user-images.githubusercontent.com/45122321/213128851-fcc4e1d7-0a58-4620-bba4-0cb3a1e9ed91.png)

**Environment**

- Nova version: 10.6
- Extension version: 2.6.0
- TypeScript version: 4.9.4
- Sidebar information: Status: Stopped
- macOS version: 13.1
- NodeJS information:
  - node version: 16.19.0
  - npm version: 8.19.3
  - installation method: nvm

**Extension console output**

```
deactivate
reloading...
dependencyManagement: claimed lock
dependencyManagement: installing: 
dependencyManagement: installing: up to date in 166ms
dependencyManagement: clearing lock
/Users/adrianwiderski/Library/Application Support/Nova/Extensions/apexskier.typescript/run.sh: line 13: node: command not found
TypeScript Language Server connection closed unexpectedly: Task exited with a non-zero exit status: 127.
```

**Additional context**

There was a similar issue in [Zed](https://zed.dev) editor, sending some info:

1. https://github.com/zed-industries/feedback/issues/445
2. https://github.com/zed-industries/feedback/issues/509

Sending screenshots from Zed's Discord from guy who found a method to fix this:

![image](https://user-images.githubusercontent.com/45122321/213130850-84f7cd38-71c2-4326-9384-f07a6d959346.png)

![image](https://user-images.githubusercontent.com/45122321/213130911-dbf577c5-8577-4b06-bc86-f8c0c55cf863.png)

**Comment by apexskier** [comment] 2023-01-18 16:40
Duplicate of #433

**Closed** 2023-01-18 16:40 UTC
Labels: bug
