### ISSUE TITLE
Seems completely broken

### ISSUE THREAD

**Issue by soniktrooth** [apexskier/nova-typescript#416] opened 2022-09-05 05:56 UTC
Typescript server just refuses to start:

```
TypeScript Language Server stopped unexpectedly:

Task exited with a non-zero exit status: 127.
```

In the extension console I’m getting:
` /Users/josh/Library/Application Support/Nova/Extensions/apexskier.typescript/run.sh: line 12: node: command not found`

Same error that was referenced here: 
https://github.com/apexskier/nova-typescript/issues/372#issuecomment-1221275391

**Comment by robert-koch** [comment] 2022-09-05 12:13
I am experiencing the same issue, and I don't think it's the extension, I think it's Nova.

Something got messed up with what shell Nova uses with the most recent update, and whatever shell it uses for extensions, doesn't seem to, at least for me, be the one where my node installation is.

I might also submit a ticket with Nova.

**Comment by soniktrooth** [comment] 2022-09-09 04:04
@robert-koch please link the Nova ticket back here so we can follow it up. Nova is basically unusable for JS dev without this extension. I’ve switched back to VSCode 😞

**Comment by soniktrooth** [comment] 2022-09-09 04:07
Also, supposedly there are 40426 installs of this extension. How are we not seeing more people complain about this?

**Comment by mindgrub-rkoch** [comment] 2022-09-12 12:36
@soniktrooth my Nova install seems to be functioning again as of this morning. I'm not sure if Nova rolled out another update or hot fix, but I'd check yours.

**Comment by robert-koch** [comment] 2022-09-12 12:38
@soniktrooth my Nova install seems to be working as of this morning. I'm not sure if they released a new update or hot fix or something, but I'd check yours.

**Comment by robert-koch** [comment] 2022-09-12 19:48
I spoke too soon. It's not working again.

**Comment by soniktrooth** [comment] 2022-09-13 01:45
@robert-koch yep, mine was working again yesterday but today after a reboot (and installing lastest MacOS) it’s doing the same thing.

**Comment by robert-koch** [comment] 2022-09-13 16:39
@soniktrooth I have found an odd potential workaround for the time being. It seems as though if you launch Nova from spotlight it fails, but if you directly open the application from the applications folder, or through the terminal, it loads fine. This is at least the case for me in my limited testing.

**Comment by soniktrooth** [comment] 2022-09-13 22:07
@robert-koch you are right! I don’t open it from spotlight because it’s on my dock, which shows the same behaviour. However launching it from the applications folder seems to make the problem go away. @apexskier are you able to advise if this is likely a Nova bug as opposed to a bug with this extension?

**Comment by apexskier** [comment] 2022-09-14 14:22
Hey, I'm guessing this is Nova, given the extension hasn't changed in three months. Definitely weird sounding. I haven't tried to reproduce yet, but can you try some tests and report back?:

For both spotlight and applications folder launches, in Nova's built in terminal, can you execute: `echo $PATH`, `command -v node` (which should print the path to the executable it finds if it finds one), and `node --version` if it finds something?

**Comment by felixqueisler** [comment] 2022-11-03 12:38
This is still happening in the last Nova 10 release (Revision 460547):
macOs 13.0 (22A380)

`TypeScript Language Server stopped unexpectedly:

Task exited with a non-zero exit status: 127.`

Pressing **Restart** oscillates randomly between this and that error message:

`TypeScript Language Server stopped unexpectedly:

The request was cancelled.`

I restarted Nova, reinstalled the extension and deactivated all other extensions. This has been going on for a while now.

Extension Sidebar reports:
Status: Stopped
TypeScript Version: Version 4.7.4

**Comment by apexskier** [comment] 2023-01-16 22:13
I hit the `node: command not found` issue locally as well when spinning this up on a new account on my work computer (my personal computer died recently). For me, it was due to changing my login shell, and not logging out and logging back in.

**Comment by apexskier** [comment] 2023-01-17 16:13
Duplicate of #433, see https://github.com/apexskier/nova-typescript/issues/433#issuecomment-1385667388

**Closed by apexskier** 2023-01-17 16:13 UTC
Labels: invalid

**Comment by MtnBiker** [comment] 2023-01-23 04:27
Also getting error for Solargraph, Server stopped unexpectedly: Task exited with a non-zero exit status: 127.

macOS 13.1. Nova 10.6 Build 476615.

Only have been using Nova for a week or two.

Anyway, reinforces problem is with Nova since two extensions have same problem. Solargraph is a dependency of a Ruby on Rails extension I think.
