### ISSUE TITLE
Unable to locate npm

### ISSUE THREAD

**Issue by arjunattam** [apexskier/nova-typescript#69] opened 2020-09-16 19:55 UTC
Unable to locate npm to spawn tsserver. Running on [this project](https://github.com/microsoft/playwright-cli).

**Environment (please complete the following information):**

- Nova version: 1.0 (Build 202519)
- Extension version: 1.6.2
- TypeScript version: ^4.0.2
- Sidebar information: 
- macOS version: 0.15.6 (19G2021)
- NodeJS information:
  - node version: v14.5.0
  - npm version: 6.14.5
  - installation method: nvm

**Extension console output**

![Screen Shot 2020-09-16 at 12 49 54 PM](https://user-images.githubusercontent.com/284612/93385587-4e51a380-f81b-11ea-9f25-949be2d3cf3b.png)

**Comment by apexskier** [comment] 2020-09-18 17:25
I've seen this as well in the past, but it hasn't appeared to prevent functionality for me. Is anything else not working?

Caused by https://github.com/microsoft/TypeScript/issues/23924.

**Comment by apexskier** [comment] 2020-09-22 19:08
Slight possibility this is related to https://github.com/apexskier/nova-typescript/issues/64#issuecomment-696921316

**Comment by jdanthinne** [comment] 2021-01-12 11:02
Fixed by making a symlink `ln -s /usr/local/bin/npm` in my /node/x.x.x/bin folder.
But now, I get a warning, but related to tsserver, not this extension…
`npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!`

**Comment by GwynethLlewelyn** [comment] 2021-01-30 14:20
I had the same issue — I'm also using `brew` to manage NodeJS, thus the error coming from `/usr/local/Cellar/node/X.Y.Z/bin` ... 

Here is my fix: as per @apexskier suggestions to take a look at the Microsoft's reported bug, I've done what I'm [self-quoting](https://github.com/microsoft/TypeScript/issues/23924#issuecomment-770216873):

`ln -s /usr/local/bin/npm /usr/local/Cellar/node/X.Y.Z/bin/npm`

just as @jdanthinne suggested.

But there is a catch. Apparently, I have _several_ TypeScript installations all scattered around the disk (why? I have no clue...). And while `npm` seems to be missing from the HomeBrew `/usr/local/Cellar/node/X.Y.Z/bin/` directory, it _is_ available from `/usr/local/bin/npm` — which _seems_ to be a completely different installation (why?).

Therefore I went to the Extensions > TypeScript > Preferences panel, and, on the _TypeScript Library_ box, I typed `/usr/local/lib/node_modules/typescript/lib/`.

This seems to work. But I'm a bit confused about _why_ it works at all.

As far as I can understand from the TypeScript extension (the code is a bit beyond my humble understanding of complex JS/TS programming), it correctly understands that I'm trying to use the Homebrew version of TypeScript — which is the one I'm sure that gets updated all the time. Unfortunately, for some unfathomable reason, _that_ version of TypeScript does _not_ place the `npm` binary where it's supposed to be. We can 'trick' the Nova-TypeScript extension in using a _different_ `npm`, but, of course, _that_ `npm` is looking for the configuration under `/usr/local/lib/node_modules/` instead. Thus the need to point to that directory.

To make matters even more confusing, I _do_ have a user-local `node_modules` directory as well. It's currently used by the [Nova-Prettier](https://github.com/alexanderweiss/nova-prettier) extension. Because I'm not proficient at all in NodeJS, I have no idea why Nova-Prettier uses a different way to configure itself (which doesn't raise any errors).

Again, my 'fix' works because I have this rather messy installation of NodeJS/TypeScript. YMMV!

What seems to be the culprit here is Microsoft's 'official' TypeScript package, which lacks `npm` in its 'proper' place. But until they release a fix, and that fix percolates to the HomeBrew team updating this package, we need this workaround...

A suggestion to @apexskier: You could add an additional preference box for people to put the path to their `npm`, instead of trying to 'guess' where it is. Or perhaps this might be delegated to an environment variable instead.

**Comment by apexskier** [comment] 2021-01-31 09:50
Interesting. I generally avoid global npm package installs when possible, so I haven't messed with a global typescript installation all that much (I'd strongly recommend keeping typescript installed via a local package.json, or using the bundled version that the extension manages (which is located at `~/Library/Application\ Support/Nova/Extensions/apexskier.typescript/dependencyManagement/node_modules/`)).

I _do_ have a brew-managed multi-node version setup, which I switch between with [this script](https://github.com/apexskier/dotfiles/blob/8013ebb27a3eeb1e2f2c101fe03ab82a45a848c1/nodejs/nodejs.bash#L6-L14). Here's kind of how it's set up...

```
cameronlittle@Nisqually:~ (⬢ v12.18.1) (go1.15.5)
▻ ls /usr/local/Cellar/node*/*/bin
/usr/local/Cellar/node/14.4.0/bin:
node*

/usr/local/Cellar/node/15.2.1/bin:
node*

/usr/local/Cellar/node@10/10.21.0/bin:
node* npm@  npx@

/usr/local/Cellar/node@12/12.18.1/bin:
node* npm@  npx@
```

> Unfortunately, for some unfathomable reason, that version of TypeScript does not place the npm binary where it's supposed to be.

This is pedantic, but TypeScript does _not_ manage an npm binary directly. More accurately, it looks like the [brew formulae](https://formulae.brew.sh/formula/typescript#default) depends explicitly on node 15 which should ship with `npm`. From my `ls` above did it didn't set up a symlink to the `npm` binary like old versions though (so when I `chnode 15`, npm isn't found). I don't know why this is but it could be a root cause here.

I reinstalled node 15 with `brew reinstall node`, and it correctly set up `npm` 7 in my `$PATH` at `/usr/local/lib/node_modules/npm/bin/npm-cli.js`. I suspect the `/usr/local/lib/node_modules` directory is shared between node install versions which might cause issues. (I get around a similar issue in go by setting a [custom GOPATH](https://github.com/apexskier/dotfiles/blob/8013ebb27a3eeb1e2f2c101fe03ab82a45a848c1/go/go.bash#L12).)

> A suggestion to @apexskier: You could add an additional preference box for people to put the path to their npm, instead of trying to 'guess' where it is. Or perhaps this might be delegated to an environment variable instead.

I'm not sure if I could do this - since `tsserver` uses the npm bin internally, I don't know if there's a way to explicitly specify it.

> Therefore I went to the Extensions > TypeScript > Preferences panel, and, on the TypeScript Library box, I typed /usr/local/lib/node_modules/typescript/lib/.

This seems like a good workaround for this issue if it causes problems.

**Closed** 2021-06-19 08:24 UTC
Labels: bug, dependency
